### ISSUE TITLE
No Serial Port Visible 

### ISSUE THREAD

**Issue by antbarney** [synthetos/g2#200]
[settings_cbeam.txt](https://github.com/synthetos/g2/files/653509/settings_cbeam.txt)

After doing a build for the gShield using the latest 100.14 when connecting up the Arduino Due I get the g2core heartbeat indicator but no Serial ports are exposed to Serial Port JSON server. I have tried from multiple machines and all show no Com ports.

Am I missing something here with the new USB changes in my build?

make BOARD=gShield SETTINGS_FILE=settings_cbeam.h is the command I am running.
[Uploading settings_cbeam.txt…]()

**Comment by giseburt** [comment]
Did you get the commits in edge from today? I fixed a similar issue with
USB on the Sam3x.

Make sure to update motate with `git submodule update`, since much of the
fix was over there.

Sorry about that. I should have opened an issue so you could see that this
was found and fixed. This just goes to show that when we don't issue an
issue for stuff we find ourselves, someone else will. :-)

-Rob

**Comment by antbarney** [comment]
Yes I saw that there was a number of changes around the USB so made sure to pull in all of the commits from today my Motate is at commit edf4f30 which is the one listed as the current one for g2Core. I even blew away my local repo and re-cloned still the same issue. Attached is the bin file from my build.

[g2core_fail.zip](https://github.com/synthetos/g2/files/653538/g2core_fail.zip)

**Comment by giseburt** [comment]
Ok, I found the issue. It's fixed in PR #201, so it'll be tracked there from here on.

Thank you for reporting this!
