### ISSUE TITLE
UART Communications w/CTS-RTS Dropping bytes

### ISSUE THREAD

**Issue by rarens** [synthetos/g2#395]
I am an Android developer by trade and am currently working on an android based GUI for controlling a 3 axis CNC running G2Core on an Arduino Due via Bluetooth.  Bluetooth is set at 115200 BAUD with CTS and RTS implemented. 

I have it working to about 99.9%; however, for every line of GC that is sent there is about a 1/1000 chance that 1 or more bytes will be dropped.  This has huge implications if the byte dropped is a decimal point!  

I discovered this problem while sending test files and every so often sending would pause while one of the axes values would start to grow to ridiculous numbers (>10000). I implemented a list in my application that compares every line of Gcode sent with every response and regardless of what gc file I send there is always some sort of data loss. 

I have tried this on the gQuintic, Edge, and Master branches and all have the same issue.

I have used a similar setup with a Mega2560 running GRBL and it worked flawlessly.   I'm using the 

following pins for UART communications:
pin_number kSerial_RXPinNumber=0;
pin_number kSerial_TXPinNumber=1;
pin_number kSerial_RTSPinNumber= 2; 
pin_number kSerial_CTSPinNumber= 3; 

I keep a constant watch on both the Serial buffer and Planner buffer to ensure there is no overflow. 

I've ruled out the possibility of a faulty bluetooth module by creating a simple sketch for due that simply echoes the Serial input.  I streamed a 65000 line Gcode file to it multiple times over Bluetooth and there was no data loss whatsoever.

I have put a ton of time in developing this application and would love to make it public but it has to work first!  Any help or insight would be appreciated.  Thanks.

**Comment by justinclift** [comment]
@aldenhart @giseburt Any ideas?

**Comment by giseburt** [comment]
Hello,

I few questions come up:

1) what version of the code are you using?
2) which Bluetooth module are you using? Does it honor the RTS and set the
CTS line properly? (Do you have a logic analyzer to record the pins and see
if either side keeps taking after the lines tell it to stop.) If it’s not
honoring RTS/CTS it may be a configuration error in the BT module or host
side.

If you are on master or newer you can enable CRC checks. You can see an
example of a CRC code being added here:
https://github.com/synthetos/node-g2core-api/blob/master/lib/g2core-api.js#L651-L661

**Comment by giseburt** [comment]
Sorry, premature send. Continued:

You will need to use gcode line numbers (“N1G0...”) that are sequential.

This means you have to strip line numbers off of the gcode before sending
and before you send anything you must send a {nxln:1} to tell it what the
next line number will be (1 in this case, it can be anything you want
though).

Note that json commands don’t need or use checksums, only gcode lines.

If you send gcode, wait for a response, and send more gcode as outlined
here (https://github.com/synthetos/g2/wiki/g2core-Communications) then you
won’t need to rely on RTS/CTS unless you have oddly long lines. Usually
stripping off comments fixes this.

-Rob

**Comment by rarens** [comment]
Thank you for your reply.  I'm following the method laid out int the g2core-Communications wiki i.e. increment lines to send and so forth.  
I certainly think checksums are a great idea.  Regardless of how perfect communications are there will always be errors from time to time. My ability to read Javascript is pretty limited but I looked at the .js file and from what I can tell the checksum byte is a bitwise XOR of all of the bytes in the command appended to the end of the line.  Is this the correct interpretation?   Is that a standard checksum method or is it unique to G2?   Is there a setting or a flag that needs to be set to enable checksums or doe G2 look for the checksum byte automatically?   Does sending the line number {nxln:n} cause checksums to be activated or is it just a reference?    Thank you again.

**Comment by giseburt** [comment]
No, every line is checked for a checksum and is verified. Missing a
checksum is not an error. (Thus the consecutive line number check, which
happens later in the code, but only if both a line number and a checksum
are found on the same line.) I recommend putting a ; before the checksum if
you’re doing it in the file (instead of as it is streamed) so gcode parsers
don’t barf on it.

Relevant C++ code here:
https://github.com/synthetos/g2/blob/edge/g2core/gcode_parser.cpp#L287-L316

So one upside of this: If a line fails checksum, every line with the wrong
number will error. So if your sender catches this it can start sending from
the failed line with no lost messages.

Example:

N1 ... ;*001
N2 ... ;*001
N3 ... ;*003 ← checksum error
N4 ... ;*001 ← line number error
N5 ... ;*001 ← line number error
N3 ... ;*001 ← no error
N4 ... ;*001 ← no error, send N5 on as normal

-Rob

**Comment by rarens** [comment]
Thank you so much for your help.  I've made a lot of progress.  I've implemented the checksums and i look for the status 118 in the footer however the following response does not throw the  STAT_LINE_NUMBER_OUT_OF_SEQUENCE(119)  error, it returns 0 for the subsequent line's status.  Here is an example:
{"r":{"gc":"N759 G3X35.168Y-93.391I-0.147J8.913;*1760}"},"f":[1,118,43]}
{"r":{"gc":"N760 X38.524Y-90.141I-4.378J7.877;*100","n":760},"f":[1,0,39]}

Also I attempted to send  {"nxln":N} as you suggested but it returns STAT_UNRECOGNIZED_NAME 100.   send-->{"nxln":1}  receive-->{"r":{"nxln":null},"f":[1,100,12]}

Is there some way to enable strict line number mode?

**Comment by giseburt** [comment]
Well hell, “nxln” apparently got lost in a merge and we missed it. See
https://github.com/synthetos/g2/commit/339c1c4df54283c54b658849f01f0e83e7cb0627#diff-8845ce59af3480923623d4abc58c0d6aL1101

Put that line back and you should get that ability back.

So I guess something else got mangled as well: line number checking appears
to be wrong. (I’m on my phone digging though the web version of the cod so
maybe I missed something...) I believe this line here:
https://github.com/synthetos/g2/blob/7a25dbf1f8ab2e60ca6122b3a477d08b5b1cd8cc/g2core/canonical_machine.cpp

Should read:
```c++
if (cm->gmx.last_line_number+1 != cm->gm.linenum) {
```

And that should fix the issue of it not catching the gcode lines after a
failure.

Thank you for helping us sort this out.

-Rob

**Comment by rarens** [comment]
Thank you so much for all of your responses.   I don't get this good of customer service on things I pay for!

Your suggestion definitely solved the nxln invalid issue I now get a valid response. 
 {"r":{"nxln":289},"f":[1,0,14]}
However, checksum errors are still going unnoticed.  I changed the line in canonical_machine.cpp to read:
`stat_t cm_check_linenum() {
    if (cm->gmx.last_line_number + 1 != cm->gm.linenum) {
        debug_trap("line number out of sequence");
        return STAT_LINE_NUMBER_OUT_OF_SEQUENCE;
    }
    cm->gmx.last_line_number = cm->gm.linenum;
    return STAT_OK;
}`

{"r":{"gc":"N249 G89.966 R5.506;*102"},"f":[1,118,25]}
{"r":{"gc":"N250 X28.951 Y-90.944 R2.488;*51","n":250},"f":[1,0,33]}

Any other ideas?
Thanks

**Comment by giseburt** [comment]
If it’s not throwing a checksum error AND the checksum doesn’t happen to
match the new failed value then it’s possible that you’re dropping
characters being sent from the Due. That’s relatively easy to test if it’s
acting relatively sane when what you get back (as you sent “G89.966” in the
gcode) is clearly not sane. You should have gotten another error for that
unknown gcode if that’s how it got it.

Maybe the Bluetooth module is not driving it’s part of the RTS/CTS when
it’s buffer gets low?

In a pinch you might consider using another wireless device (Pi Zero
wireless?) with usb or such. Just a thought if you’re low on time to get
this working before a deadline.

-Rob

**Comment by rarens** [comment]
I agree that line 249 as it's returned is invalid the correct line is:
N249 G3 X28.927 Y-89.966 R5.506;*102
and I recieved:
"r":{"gc":"N249 G89.966 R5.506;*102"},"f":[1,118,25]}

> If it’s not throwing a checksum error...

It IS thowing a checksum error indicated by the 118 in the footer.  

The due received the code and found the checksum error indicated by the 118 in the footer.  My problem is that it continues to accept other lines without throwing the 119 seqence error for subsequent lines.  

I would assume that G2 validates the checksum before any attempt to parse the gcode is made.  It just seems like it sets the status to 118 for that one line, skips it and moves right onto the next one.

I'm currently on the edge branch.  Is there a specific commit where the expected behavior is know to work? 

Also, I've tried multiple bluetooth modules(2 HC-06 and 1 HC-05) all with the same results.  I'm not on any deadline but I've been working on this for some time and would like it to be finished. 

Thank you again.

**Comment by giseburt** [comment]
I’ll look into this more. I’m not sure why you’re not seeing it fail
subsequent lines after the checksum failure. I’ll report back my findings.

**Comment by giseburt** [comment]
I’m. Or able to debug at this point, but I don’t see how
cm->gmx.last_line_number could get updated when a checksum error happens,
so as long as it sees the checksum for the next line it should check the
line number and fail it until the checksum-failed line is resent.

So just for sanity’s sake, if you send two checksummed lines with
non-sequential line numbers, and the checksum doesn’t fail, do you get a
119 error like you should?

Separate question: Is your process semi-reliably failing on the same line?
The examples in your email indicate that they are, N249 seems to get
truncated. If so, could you share your file past N255 or so for testing?
Thank you!

**Comment by rarens** [comment]
I'll try non sequential numbers and let you know what I find.  

Sadly no, It errors at completely random points.

**Comment by rarens** [comment]
I just did the line number test and received no error.  My method was this:
wait for line 100, skip to line 105, wait for line 110, skip back to line 99.  I got no error for skipping forward or skipping backwards. 
{"r":{"nxln":99},"f":[1,0,13]}
{"r":{"gc":"N99 X32.451 Y-85.419 R0.265;*4","n":99},"f":[1,0,31]}
{"r":{"nxln":105},"f":[1,0,14]}
{"r":{"gc":"N105 X30.5 Y-86.917 R7.164;*50","n":105},"f":[1,0,31]}
{"r":{"nxln":106},"f":[1,0,14]}
{"r":{"gc":"N106 X37.374 Y-86.583 R8.39;*4","n":106},"f":[1,0,31]}
{"r":{"nxln":107},"f":[1,0,14]}
{"r":{"gc":"N107 X37.739 Y-84.363 R5.12;*6","n":107},"f":[1,0,31]}
{"r":{"nxln":108},"f":[1,0,14]}
{"r":{"gc":"N108 X37.029 Y-82.759 R2.746;*53","n":108},"f":[1,0,33]}
{"r":{"nxln":109},"f":[1,0,14]}
{"r":{"nxln":99},"f":[1,0,13]}
{"r":{"gc":"N109 X35.099 Y-82.058 R2.545;*58","n":109},"f":[1,0,33]}
{"r":{"nxln":100},"f":[1,0,14]}
{"r":{"nxln":101},"f":[1,0,14]}
{"r":{"gc":"N99 X32.674 Y-82.631 R5.684;*0","n":99},"f":[1,0,31]}
{"r":{"gc":"N100 X30.5 Y-86.917 R7.164;*55","n":100},"f":[1,0,31]}
{"r":{"gc":"N101 X28.73 Y-89.922 R5.892;*5","n":101},"f":[1,0,31]}
{"r":{"nxln":102},"f":[1,0,14]}
{"r":{"gc":"N102 X28.805 Y-91.142 R2.54;*13","n":102},"f":[1,0,32]}
{"r":{"nxln":103},"f":[1,0,14]}
{"r":{"gc":"N103 X29.972 Y-91.935 R1.343;*50","n":103},"f":[1,0,33]}
{"r":{"nxln":104},"f":[1,0,14]}
{"r":{"gc":"N104 X31.966 Y-91.584 R3.991;*56","n":104},"f":[1,0,33]}

I also did a test where nxln and the next line do not match and received no error as well.

{"r":{"gc":"N99 G1X25.966Y-91.836;*4","n":99},"f":[1,0,25]}
{"r":{"nxln":100},"f":[1,0,14]}
{"r":{"gc":"N105 X25.97Y-91.879;*122","n":105},"f":[1,0,25]}
{"r":{"nxln":106},"f":[1,0,14]}
{"r":{"gc":"N106 X26.23Y-91.776Z-0.171;*43","n":106},"f":[1,0,31]}
{"r":{"nxln":107},"f":[1,0,14]}
{"r":{"gc":"N107 X26.198Y-91.78Z-0.192;*47","n":107},"f":[1,0,31]}
{"r":{"nxln":108},"f":[1,0,14]}
{"r":{"gc":"N108 X26.16Y-91.785Z-0.2;*42","n":108},"f":[1,0,29]}
{"r":{"nxln":109},"f":[1,0,14]}

**Comment by giseburt** [comment]
Is MARLIN_COMPAT_ENABLED on in your code? Are you working from edge (5c4ba36 at the moment) or master (b7ff8a5)?

**Comment by rarens** [comment]
MARLIN_COMPAT_ENABLED is set to true.  And I'm working from edge but it's 7a25dbf which appears to be 2 commits ahead of 5c4ba36.

**Comment by giseburt** [comment]
Ah ok, so that’s all good.

Are you able to debug a running machine? If so I’d like to see if
cm_check_linenum() ever gets called and if not why? It should be called
from https://github.com/synthetos/g2/blob/edge/g2core/gcode_parser.cpp#L1077
with Marlin compatibility on. If it’s not then something mangled gf.linenum
or gf.checksum which should both be true.

I can’t run this on a live machine at the moment or I would test it myself.

**Comment by rarens** [comment]
I have no Idea how to debug a running machine.

**Comment by rarens** [comment]
I changed the check_line_num function to always return an error and I've seen no difference. Eithor it's not called or the result is ignored.
stat_t cm_check_linenum() {
     if (cm->gmx.last_line_number+1 != cm->gm.linenum) {
        debug_trap("line number out of sequence");
        return STAT_LINE_NUMBER_OUT_OF_SEQUENCE;
    }
    cm->gmx.last_line_number = cm->gm.linenum;
   return STAT_LINE_NUMBER_OUT_OF_SEQUENCE;
}

**Comment by rarens** [comment]
It doesn't look like gf.linenum is ever set to true anywhere in the code.  I just added it if a line starts with "N"

**Comment by giseburt** [comment]
It should be getting set here:
https://github.com/synthetos/g2/blob/edge/g2core/gcode_parser.cpp#L868

With this macro: SET_NON_MODAL(parm,val) ({gv.parm=val; gf.parm=true;
break;})

If cm_set_model_linenum() is getting called from here
https://github.com/synthetos/g2/blob/edge/g2core/gcode_parser.cpp#L932 then
the gf.linenum is set.

It should be getting called from here for you:
https://github.com/synthetos/g2/blob/edge/g2core/gcode_parser.cpp#L1077

Note that gf.checksum is cleared a few lines later.

Does forcing the gf.linenum make it work properly?

**Comment by rarens** [comment]
No it had no difference.  I didn't realize how the value got set.

**Comment by justinclift** [comment]
@rarens As a general thought, as I haven't seen mention of it here yet, would it be feasible for us to get a copy of the config settings you're using at the moment?

Note - there's no stand out need for it, I'm more asking for completeness and the extra info can **sometimes** be useful when people are investigating stuff. :smile:

**Comment by rarens** [comment]
sure here is setting and pinout.  I use make board=gShield to build.  
[gShield-pinout.h.txt](https://github.com/synthetos/g2/files/2757483/gShield-pinout.h.txt)
[settings_default.h.txt](https://github.com/synthetos/g2/files/2757484/settings_default.h.txt)

**Comment by justinclift** [comment]
Thanks @rarens. :smile:

**Comment by giseburt** [comment]
Perhaps before this line:
https://github.com/synthetos/g2/blob/edge/g2core/gcode_parser.cpp#L950

And to see if gf.linenum is false then throw an error and if gf.checksum is
false then throw a different error. Both should be set with the gcode
you’re sending. I guess once you know which one is not right then work your
way back to where they’re set and see when they’re reset.

For linenum it’s where I mentioned previously. For checksum it’s set here:
https://github.com/synthetos/g2/blob/edge/g2core/gcode_parser.cpp#L305

Thank you for working through this with us.

**Comment by rarens** [comment]
So I created two errors in errror.cpp and inserted the checks before line 950 in gcode parser.
if(!gf.linenum)return STAT_NO_LINE_NUM;
if(!gf.checksum)return STAT_NO_CHECKSUM;
100&of them are returning NO_CHECKSUM;

**Comment by giseburt** [comment]
Aha!

Move lines 660-661:
https://github.com/synthetos/g2/blob/edge/g2core/gcode_parser.cpp#L660-L661

memset(&gv, 0, sizeof(GCodeValue_t)); // clear all next-state values
memset(&gf, 0, sizeof(GCodeFlag_t)); // clear all next-state flags


To just before line 255:
https://github.com/synthetos/g2/blob/edge/g2core/gcode_parser.cpp#L255

stat_t check_ret = _verify_checksum(str);

So it stops resetting the gv and gf structures after verify is called.

That should do it.

**Comment by rarens** [comment]
Well we're REAL close! now after a checksum error the subsequent lines sent all have 119(incorrect line nuber) as the status. However, when the 118 is thrown by the bad checksum it's missing the "n" attribute found on other responses.  Can this easily be added?
{"r":{"gc":"N466 X377Z-0.184;*17"},"f":[1,118,21]}
{"r":{"gc":"N467 X37.736Y-80.327;*68","n":467},"f":[1,119,25]}

Thanks a bunch!  
If it's a pain to add I'll just keep track another way.

**Comment by rarens** [comment]
Also, even though the status is 119 the commands continue to execute how can we make gcode lines with a status !=0 not be executed?

This may be on my end. Still looking

**Comment by rarens** [comment]
Yes that issue was actually not an issue, it was it working!  I'm just keeping track of the last "n" with a status of 0.  
Thanks again for all of your help!

**Comment by justinclift** [comment]
Excellent! :smile:

@rarens How good are you with git?

Just thinking it might be useful to create a Pull Request here on GitHub with the new bugfix changes as figured out in this issue.  It sounds like the problem would affect other people too, so we might as well get the investigation work done here made permanent. :wink:

**Comment by rarens** [comment]
@justinclift 
I'm pretty good at git.  I use it daily and manage a lot of branches for my daily job. I'll look into a pull request.
